server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb+srv://cad_node_a:Qwertyuiop123%21@webmusic.ro4f2iz.mongodb.net/cad_node_a?appName=webmusic

app:
  site-id: node-a

node:
  name: node-a
  peers:
    - http://localhost:5001